# Generated by Django 2.0 on 2017-12-21 08:44

import cronovisor.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cronovisor', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='image',
            name='image',
            field=models.ImageField(null=True, upload_to=cronovisor.models.upload_to),
        ),
    ]
