# Generated by Django 2.0 on 2017-12-21 11:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cronovisor', '0002_image_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='image',
            name='description',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='image',
            name='id_marker',
            field=models.ForeignKey(default=1, on_delete='cascade', to='cronovisor.Marker'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='image',
            name='id_street',
            field=models.ForeignKey(default=1, on_delete='cascade', to='cronovisor.Street'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='marker',
            name='description',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
