# Generated by Django 2.0 on 2017-12-27 09:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cronovisor', '0003_auto_20171221_1101'),
    ]

    operations = [
        migrations.AlterField(
            model_name='image',
            name='id_marker',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cronovisor.Marker'),
        ),
        migrations.AlterField(
            model_name='image',
            name='id_street',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='title', to='cronovisor.Street'),
        ),
    ]
